# Generated by Django 5.0.6 on 2024-06-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at_task_updated_at_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assined_to',
            new_name='assigned_to',
        ),
    ]
